version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cinema
      POSTGRES_DB: cinema
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
      - 5000:5000